### PR TITLE
widered the compare side bar & change the shopping cart icon to text

### PR DESCRIPTION
**Pull request by zhouzilong2020**

### CODE REVIEW

**Comment by zhouzilong2020** [comment]
PTAL

**Comment by zhouzilong2020** [comment]
PTAL

**Review by tianzhou — COMMENTED** [review]
How about putting it on the top right instead of bottom right since the "Compare instance" in the sidebar is on the top right

**Comment by zhouzilong2020** [comment]
> How about putting it on the top right instead of bottom right since the "Compare instance" in the sidebar is on the top right

SGTM

**Comment by zhouzilong2020** [comment]
PTAL

**Review by LiuJi-Jim — COMMENTED** [review]
LGTM

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
