### PR TITLE
feat: copy url to clipboard

### PR DESCRIPTION
**Pull request by h3n4l**
https://user-images.githubusercontent.com/87714218/198285151-44d57ada-c011-4490-bf75-8ad759def38d.mp4

### CODE REVIEW

**Comment by Megrax** [comment]
Let's add UI feedback on copy success.

**Comment by h3n4l** [comment]
PTAL

**Review by d-bytebase — APPROVED** [review]

**Comment by d-bytebase** [comment]
Type error: Type 'false | "dashed"' is not assignable to type '"link" | "text" | "default" | "ghost" | "dashed" | "primary" | undefined'.

**Review by LiuJi-Jim — APPROVED** [review]
LGTM

**Pull request merged**
