### PR TITLE
feat: show diff from the on demand charge type

### PR DESCRIPTION
**Pull request by zhouzilong2020**

### CODE REVIEW

**Comment by zhouzilong2020** [comment]
PTAL

**Review by tianzhou — COMMENTED** [review]
CleanShot 2022-06-08 at 17 18 56

It's hard to see the baseline

**Comment by zhouzilong2020** [comment]
PTAL

**Review by tianzhou — APPROVED** [review]
LGTM

**Comment by tianzhou** [comment]
This is a useful addition

**Pull request merged**
