### PR TITLE
fix: utilization should not affect reserved charge type

### PR DESCRIPTION
**Pull request by zhouzilong2020**

### CODE REVIEW

**Comment by zhouzilong2020** [comment]
PTAL

**Comment by d-bytebase** [comment]
@LiuJi-Jim PTAL

**Review by LiuJi-Jim — COMMENTED** [review]
LGTM

**Comment by zhouzilong2020** [comment]
Solved conflict, noting changed.
 PTAL

**Review by tianzhou — APPROVED** [review]
LGTM

**Pull request merged**
